- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names 1
    ansible.builtin.debug:
      msg: "Hello {{ item }}" # item is reserved
    loop:
    - Ramesh
    - Suresh
    - Raheem
    - John
  - name: print names 2
    ansible.builtin.package:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql
    - zip
  - name: print names 3
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
    - { name: "nginx", state: "absent"}
    - { name: "mysql", state: "absent"}
    - { name: "zip", state: "latest"}